@EventSourcingExercise_HostAddress = http://localhost:5041
@TenantCode = TenantA

### Health check
GET {{EventSourcingExercise_HostAddress}}/_hc/
Accept: application/json

### step01 - Payment
POST {{EventSourcingExercise_HostAddress}}/transaction/pay
Accept: application/json
Content-Type: application/json
Tenant-Code: {{TenantCode}}

{
  "amount": 5
}
> {%
    client.global.set("transactionId", response.body.data.transactionId);
%}

### step02 - Capture
POST {{EventSourcingExercise_HostAddress}}/transaction/capture
Accept: application/json
Content-Type: application/json
Tenant-Code: {{TenantCode}}

{
  "transactionId": "{{transactionId}}"
}

### Operation - Query Payment Aggregate
GET {{EventSourcingExercise_HostAddress}}/operation/payment/{{transactionId}}
